// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpsFD91RMLc-9fZPe7_JoXH3cA3YZDWY',
    appId: '1:230971458957:android:f10a0e8126b0b18ceb29c4',
    messagingSenderId: '230971458957',
    projectId: 'expense-tracker-aaef4',
    storageBucket: 'expense-tracker-aaef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPTrj89fgJAvGAnw4gJ72r3WbeShbLMY',
    appId: '1:230971458957:ios:edb345c7260ee138eb29c4',
    messagingSenderId: '230971458957',
    projectId: 'expense-tracker-aaef4',
    storageBucket: 'expense-tracker-aaef4.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPTrj89fgJAvGAnw4gJ72r3WbeShbLMY',
    appId: '1:230971458957:ios:edb345c7260ee138eb29c4',
    messagingSenderId: '230971458957',
    projectId: 'expense-tracker-aaef4',
    storageBucket: 'expense-tracker-aaef4.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
